language: c
sudo: true

matrix:
  include:
#
    - os: linux
      compiler: clang
      addons:
        apt:
          packages:
           - clang-8
#
    - os: linux
      compiler: gcc-6
      addons:
          apt:
            sources:
              - ubuntu-toolchain-r-test
            packages:
              - gcc-6
      env:
        - CC=gcc-6
#
    - os: linux
      compiler: gcc
      addons:
          apt:
            packages:
              - gcc-4.8

# Install dependencies
addons:
  apt:
    packages:
      - cmake

before_script:
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get update -qq
  - sudo apt-get install -y libegl1-mesa-dev libgles2-mesa-dev
  - sudo apt-get install -y libglew-dev check libsdl2-dev libsubunit-dev

# Build library.
script:
  - mkdir build && cd build
  - cmake ..
  - cmake --build .
  - ctest -VV

